// Generated by CoffeeScript 1.12.4
(function() {
  var randomBytes, wordlist;

  randomBytes = require('crypto').randomBytes;

  wordlist = require('./wordlist.json').wordlist;

  module.exports = function(l) {
    var random, words;
    if (l < 1) {
      return '';
    }
    words = [];
    while (words.length < l) {
      random = randomBytes(2).readUInt16LE(0) & 0x7fff;
      if (random >= wordlist.length) {
        continue;
      }
      words.push(wordlist[random]);
    }
    return words.join(' ');
  };

  module.exports.wordlist = wordlist;

}).call(this);
